### ISSUE TITLE
[Front End][Myke]View Notes Prototype

### ISSUE THREAD

**Issue by Esseh** [mjrmyke/CSCI150Project#20]
Provide a View Notes page based on the CSS for the editor.
Give an anchor to the relevant edit page. 
I'll finish integrating the prototype once you're done.
additionally be sure to Be sure to {{define "viewNotes"}}

**Comment by mjrmyke** [comment]
Done with everything but an anchor to a relevant edit page.

**Comment by mjrmyke** [comment]
Done!
